/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex("users").del();
    await knex("users").insert([
        {
            firstName: "John",
            lastName: "Doe",
            email: "johndoe@example.com",
            password: "password123",
            age: 28,
            gender: "male",
            experience: "beginner",
            city: "New York",
            state: "NY",
            zipcode: 10001,
            profilePicture: "https://example.com/profile1.jpg",
            profileTagLine: "Passionate coder exploring new possibilities",
            twitter: "abcd1",
            pinterest: "efghi",
            instagram: "jklmn",
            facebook: "opqrs",
        },
        {
            firstName: "Alice",
            lastName: "Smith",
            email: "alicesmith@example.com",
            password: "qwerty456",
            age: 32,
            gender: "female",
            experience: "intermediate",
            city: "Los Angeles",
            state: "CA",
            zipcode: 90001,
            profilePicture: "https://example.com/profile2.jpg",
            profileTagLine: "Designer with an eye for detail",
            twitter: "uvwxy",
            pinterest: "zabcd",
            instagram: "efghi",
            facebook: "jklmn",
        },
        {
            firstName: "David",
            lastName: "Johnson",
            email: "davidjohnson@example.com",
            password: "pass123word",
            age: 40,
            gender: "male",
            experience: "experienced",
            city: "Chicago",
            state: "IL",
            zipcode: 60601,
            profilePicture: "https://example.com/profile3.jpg",
            profileTagLine: "Innovative problem solver",
            twitter: "opqrs",
            pinterest: "uvwxy",
            instagram: "zabcd",
            facebook: "efghi",
        },
        {
            firstName: "Emily",
            lastName: "Brown",
            email: "emilybrown@example.com",
            password: "abc123xyz",
            age: 25,
            gender: "female",
            experience: "beginner",
            city: "San Francisco",
            state: "CA",
            zipcode: 94101,
            profilePicture: "https://example.com/profile4.jpg",
            profileTagLine: "Exploring the world of web development",
            twitter: "jklmn",
            pinterest: "opqrs",
            instagram: "uvwxy",
            facebook: "zabcd",
        },
        {
            firstName: "Michael",
            lastName: "Taylor",
            email: "michaeltaylor@example.com",
            password: "password789",
            age: 35,
            gender: "male",
            experience: "intermediate",
            city: "Houston",
            state: "TX",
            zipcode: 77001,
            profilePicture: "https://example.com/profile5.jpg",
            profileTagLine: "Passionate about building meaningful applications",
            twitter: "efghi",
            pinterest: "jklmn",
            instagram: "opqrs",
            facebook: "uvwxy",
        },
    ]);
};
